/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeUpdate{}

// EmployeeUpdate struct for EmployeeUpdate
type EmployeeUpdate struct {
	Data EmployeeUpdateData `json:"data"`
}

type _EmployeeUpdate EmployeeUpdate

// NewEmployeeUpdate instantiates a new EmployeeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeUpdate(data EmployeeUpdateData) *EmployeeUpdate {
	this := EmployeeUpdate{}
	this.Data = data
	return &this
}

// NewEmployeeUpdateWithDefaults instantiates a new EmployeeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeUpdateWithDefaults() *EmployeeUpdate {
	this := EmployeeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *EmployeeUpdate) GetData() EmployeeUpdateData {
	if o == nil {
		var ret EmployeeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdate) GetDataOk() (*EmployeeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *EmployeeUpdate) SetData(v EmployeeUpdateData) {
	o.Data = v
}

func (o EmployeeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EmployeeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeUpdate := _EmployeeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeUpdate)

	if err != nil {
		return err
	}

	*o = EmployeeUpdate(varEmployeeUpdate)

	return err
}

type NullableEmployeeUpdate struct {
	value *EmployeeUpdate
	isSet bool
}

func (v NullableEmployeeUpdate) Get() *EmployeeUpdate {
	return v.value
}

func (v *NullableEmployeeUpdate) Set(val *EmployeeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeUpdate(val *EmployeeUpdate) *NullableEmployeeUpdate {
	return &NullableEmployeeUpdate{value: val, isSet: true}
}

func (v NullableEmployeeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


