/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUpdateData{}

// OrganizationUpdateData struct for OrganizationUpdateData
type OrganizationUpdateData struct {
	// organization id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes OrganizationCreateDataAttributes `json:"attributes"`
}

type _OrganizationUpdateData OrganizationUpdateData

// NewOrganizationUpdateData instantiates a new OrganizationUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUpdateData(id string, type_ string, attributes OrganizationCreateDataAttributes) *OrganizationUpdateData {
	this := OrganizationUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewOrganizationUpdateDataWithDefaults instantiates a new OrganizationUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUpdateDataWithDefaults() *OrganizationUpdateData {
	this := OrganizationUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *OrganizationUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrganizationUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrganizationUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OrganizationUpdateData) GetAttributes() OrganizationCreateDataAttributes {
	if o == nil {
		var ret OrganizationCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OrganizationUpdateData) GetAttributesOk() (*OrganizationCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OrganizationUpdateData) SetAttributes(v OrganizationCreateDataAttributes) {
	o.Attributes = v
}

func (o OrganizationUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *OrganizationUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationUpdateData := _OrganizationUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationUpdateData)

	if err != nil {
		return err
	}

	*o = OrganizationUpdateData(varOrganizationUpdateData)

	return err
}

type NullableOrganizationUpdateData struct {
	value *OrganizationUpdateData
	isSet bool
}

func (v NullableOrganizationUpdateData) Get() *OrganizationUpdateData {
	return v.value
}

func (v *NullableOrganizationUpdateData) Set(val *OrganizationUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUpdateData(val *OrganizationUpdateData) *NullableOrganizationUpdateData {
	return &NullableOrganizationUpdateData{value: val, isSet: true}
}

func (v NullableOrganizationUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


