/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the EmployeeCollectionLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCollectionLinks{}

// EmployeeCollectionLinks struct for EmployeeCollectionLinks
type EmployeeCollectionLinks struct {
	// Link to the current page
	Self *string `json:"self,omitempty"`
	// Link to the next page
	Next *string `json:"next,omitempty"`
}

// NewEmployeeCollectionLinks instantiates a new EmployeeCollectionLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCollectionLinks() *EmployeeCollectionLinks {
	this := EmployeeCollectionLinks{}
	return &this
}

// NewEmployeeCollectionLinksWithDefaults instantiates a new EmployeeCollectionLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCollectionLinksWithDefaults() *EmployeeCollectionLinks {
	this := EmployeeCollectionLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *EmployeeCollectionLinks) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCollectionLinks) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *EmployeeCollectionLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *EmployeeCollectionLinks) SetSelf(v string) {
	o.Self = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *EmployeeCollectionLinks) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCollectionLinks) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *EmployeeCollectionLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *EmployeeCollectionLinks) SetNext(v string) {
	o.Next = &v
}

func (o EmployeeCollectionLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCollectionLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	return toSerialize, nil
}

type NullableEmployeeCollectionLinks struct {
	value *EmployeeCollectionLinks
	isSet bool
}

func (v NullableEmployeeCollectionLinks) Get() *EmployeeCollectionLinks {
	return v.value
}

func (v *NullableEmployeeCollectionLinks) Set(val *EmployeeCollectionLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCollectionLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCollectionLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCollectionLinks(val *EmployeeCollectionLinks) *NullableEmployeeCollectionLinks {
	return &NullableEmployeeCollectionLinks{value: val, isSet: true}
}

func (v NullableEmployeeCollectionLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCollectionLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


