/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeData{}

// EmployeeData struct for EmployeeData
type EmployeeData struct {
	// user id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes EmployeeDataAttributes `json:"attributes"`
}

type _EmployeeData EmployeeData

// NewEmployeeData instantiates a new EmployeeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeData(id string, type_ string, attributes EmployeeDataAttributes) *EmployeeData {
	this := EmployeeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmployeeDataWithDefaults instantiates a new EmployeeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeDataWithDefaults() *EmployeeData {
	this := EmployeeData{}
	return &this
}

// GetId returns the Id field value
func (o *EmployeeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmployeeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmployeeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *EmployeeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmployeeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmployeeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmployeeData) GetAttributes() EmployeeDataAttributes {
	if o == nil {
		var ret EmployeeDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmployeeData) GetAttributesOk() (*EmployeeDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmployeeData) SetAttributes(v EmployeeDataAttributes) {
	o.Attributes = v
}

func (o EmployeeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmployeeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeData := _EmployeeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeData)

	if err != nil {
		return err
	}

	*o = EmployeeData(varEmployeeData)

	return err
}

type NullableEmployeeData struct {
	value *EmployeeData
	isSet bool
}

func (v NullableEmployeeData) Get() *EmployeeData {
	return v.value
}

func (v *NullableEmployeeData) Set(val *EmployeeData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeData(val *EmployeeData) *NullableEmployeeData {
	return &NullableEmployeeData{value: val, isSet: true}
}

func (v NullableEmployeeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


