/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantCreateData{}

// ParticipantCreateData struct for ParticipantCreateData
type ParticipantCreateData struct {
	Type string `json:"type"`
	Attributes ParticipantCreateDataAttributes `json:"attributes"`
}

type _ParticipantCreateData ParticipantCreateData

// NewParticipantCreateData instantiates a new ParticipantCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantCreateData(type_ string, attributes ParticipantCreateDataAttributes) *ParticipantCreateData {
	this := ParticipantCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewParticipantCreateDataWithDefaults instantiates a new ParticipantCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantCreateDataWithDefaults() *ParticipantCreateData {
	this := ParticipantCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *ParticipantCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ParticipantCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ParticipantCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ParticipantCreateData) GetAttributes() ParticipantCreateDataAttributes {
	if o == nil {
		var ret ParticipantCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ParticipantCreateData) GetAttributesOk() (*ParticipantCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ParticipantCreateData) SetAttributes(v ParticipantCreateDataAttributes) {
	o.Attributes = v
}

func (o ParticipantCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ParticipantCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantCreateData := _ParticipantCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantCreateData)

	if err != nil {
		return err
	}

	*o = ParticipantCreateData(varParticipantCreateData)

	return err
}

type NullableParticipantCreateData struct {
	value *ParticipantCreateData
	isSet bool
}

func (v NullableParticipantCreateData) Get() *ParticipantCreateData {
	return v.value
}

func (v *NullableParticipantCreateData) Set(val *ParticipantCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantCreateData(val *ParticipantCreateData) *NullableParticipantCreateData {
	return &NullableParticipantCreateData{value: val, isSet: true}
}

func (v NullableParticipantCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


