/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the ParticipantsCollectionMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantsCollectionMeta{}

// ParticipantsCollectionMeta struct for ParticipantsCollectionMeta
type ParticipantsCollectionMeta struct {
	// Total number of participants
	Total *int32 `json:"total,omitempty"`
}

// NewParticipantsCollectionMeta instantiates a new ParticipantsCollectionMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantsCollectionMeta() *ParticipantsCollectionMeta {
	this := ParticipantsCollectionMeta{}
	return &this
}

// NewParticipantsCollectionMetaWithDefaults instantiates a new ParticipantsCollectionMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantsCollectionMetaWithDefaults() *ParticipantsCollectionMeta {
	this := ParticipantsCollectionMeta{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ParticipantsCollectionMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantsCollectionMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ParticipantsCollectionMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ParticipantsCollectionMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o ParticipantsCollectionMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantsCollectionMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableParticipantsCollectionMeta struct {
	value *ParticipantsCollectionMeta
	isSet bool
}

func (v NullableParticipantsCollectionMeta) Get() *ParticipantsCollectionMeta {
	return v.value
}

func (v *NullableParticipantsCollectionMeta) Set(val *ParticipantsCollectionMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantsCollectionMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantsCollectionMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantsCollectionMeta(val *ParticipantsCollectionMeta) *NullableParticipantsCollectionMeta {
	return &NullableParticipantsCollectionMeta{value: val, isSet: true}
}

func (v NullableParticipantsCollectionMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantsCollectionMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


