/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUpdate{}

// OrganizationUpdate struct for OrganizationUpdate
type OrganizationUpdate struct {
	Data OrganizationUpdateData `json:"data"`
}

type _OrganizationUpdate OrganizationUpdate

// NewOrganizationUpdate instantiates a new OrganizationUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUpdate(data OrganizationUpdateData) *OrganizationUpdate {
	this := OrganizationUpdate{}
	this.Data = data
	return &this
}

// NewOrganizationUpdateWithDefaults instantiates a new OrganizationUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUpdateWithDefaults() *OrganizationUpdate {
	this := OrganizationUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *OrganizationUpdate) GetData() OrganizationUpdateData {
	if o == nil {
		var ret OrganizationUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OrganizationUpdate) GetDataOk() (*OrganizationUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OrganizationUpdate) SetData(v OrganizationUpdateData) {
	o.Data = v
}

func (o OrganizationUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *OrganizationUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationUpdate := _OrganizationUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationUpdate)

	if err != nil {
		return err
	}

	*o = OrganizationUpdate(varOrganizationUpdate)

	return err
}

type NullableOrganizationUpdate struct {
	value *OrganizationUpdate
	isSet bool
}

func (v NullableOrganizationUpdate) Get() *OrganizationUpdate {
	return v.value
}

func (v *NullableOrganizationUpdate) Set(val *OrganizationUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUpdate(val *OrganizationUpdate) *NullableOrganizationUpdate {
	return &NullableOrganizationUpdate{value: val, isSet: true}
}

func (v NullableOrganizationUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


