/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationCreateDataAttributes{}

// OrganizationCreateDataAttributes struct for OrganizationCreateDataAttributes
type OrganizationCreateDataAttributes struct {
	// Team name
	Name string `json:"name"`
	// Team description
	Desc string `json:"desc"`
	// Type of Organization
	Sort string `json:"sort"`
}

type _OrganizationCreateDataAttributes OrganizationCreateDataAttributes

// NewOrganizationCreateDataAttributes instantiates a new OrganizationCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationCreateDataAttributes(name string, desc string, sort string) *OrganizationCreateDataAttributes {
	this := OrganizationCreateDataAttributes{}
	this.Name = name
	this.Desc = desc
	this.Sort = sort
	return &this
}

// NewOrganizationCreateDataAttributesWithDefaults instantiates a new OrganizationCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationCreateDataAttributesWithDefaults() *OrganizationCreateDataAttributes {
	this := OrganizationCreateDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *OrganizationCreateDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationCreateDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *OrganizationCreateDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *OrganizationCreateDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetSort returns the Sort field value
func (o *OrganizationCreateDataAttributes) GetSort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributes) GetSortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sort, true
}

// SetSort sets field value
func (o *OrganizationCreateDataAttributes) SetSort(v string) {
	o.Sort = v
}

func (o OrganizationCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["sort"] = o.Sort
	return toSerialize, nil
}

func (o *OrganizationCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"sort",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationCreateDataAttributes := _OrganizationCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = OrganizationCreateDataAttributes(varOrganizationCreateDataAttributes)

	return err
}

type NullableOrganizationCreateDataAttributes struct {
	value *OrganizationCreateDataAttributes
	isSet bool
}

func (v NullableOrganizationCreateDataAttributes) Get() *OrganizationCreateDataAttributes {
	return v.value
}

func (v *NullableOrganizationCreateDataAttributes) Set(val *OrganizationCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationCreateDataAttributes(val *OrganizationCreateDataAttributes) *NullableOrganizationCreateDataAttributes {
	return &NullableOrganizationCreateDataAttributes{value: val, isSet: true}
}

func (v NullableOrganizationCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


