/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantUpdate{}

// ParticipantUpdate struct for ParticipantUpdate
type ParticipantUpdate struct {
	Data ParticipantUpdateData `json:"data"`
}

type _ParticipantUpdate ParticipantUpdate

// NewParticipantUpdate instantiates a new ParticipantUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantUpdate(data ParticipantUpdateData) *ParticipantUpdate {
	this := ParticipantUpdate{}
	this.Data = data
	return &this
}

// NewParticipantUpdateWithDefaults instantiates a new ParticipantUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantUpdateWithDefaults() *ParticipantUpdate {
	this := ParticipantUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *ParticipantUpdate) GetData() ParticipantUpdateData {
	if o == nil {
		var ret ParticipantUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ParticipantUpdate) GetDataOk() (*ParticipantUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ParticipantUpdate) SetData(v ParticipantUpdateData) {
	o.Data = v
}

func (o ParticipantUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ParticipantUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantUpdate := _ParticipantUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantUpdate)

	if err != nil {
		return err
	}

	*o = ParticipantUpdate(varParticipantUpdate)

	return err
}

type NullableParticipantUpdate struct {
	value *ParticipantUpdate
	isSet bool
}

func (v NullableParticipantUpdate) Get() *ParticipantUpdate {
	return v.value
}

func (v *NullableParticipantUpdate) Set(val *ParticipantUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantUpdate(val *ParticipantUpdate) *NullableParticipantUpdate {
	return &NullableParticipantUpdate{value: val, isSet: true}
}

func (v NullableParticipantUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


