/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the OrganizationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDataAttributes{}

// OrganizationDataAttributes struct for OrganizationDataAttributes
type OrganizationDataAttributes struct {
	// Team name
	Name string `json:"name"`
	// link to photo
	Logo string `json:"logo"`
	// Team description
	Desc string `json:"desc"`
	// Type of Organization
	Sort string `json:"sort"`
	Links Object `json:"links"`
	ComplicatedStatus Object `json:"complicated_status"`
	// Team creation timestamp
	CreatedAt time.Time `json:"created_at"`
}

type _OrganizationDataAttributes OrganizationDataAttributes

// NewOrganizationDataAttributes instantiates a new OrganizationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDataAttributes(name string, logo string, desc string, sort string, links Object, complicatedStatus Object, createdAt time.Time) *OrganizationDataAttributes {
	this := OrganizationDataAttributes{}
	this.Name = name
	this.Logo = logo
	this.Desc = desc
	this.Sort = sort
	this.Links = links
	this.ComplicatedStatus = complicatedStatus
	this.CreatedAt = createdAt
	return &this
}

// NewOrganizationDataAttributesWithDefaults instantiates a new OrganizationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDataAttributesWithDefaults() *OrganizationDataAttributes {
	this := OrganizationDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *OrganizationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetLogo returns the Logo field value
func (o *OrganizationDataAttributes) GetLogo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Logo
}

// GetLogoOk returns a tuple with the Logo field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Logo, true
}

// SetLogo sets field value
func (o *OrganizationDataAttributes) SetLogo(v string) {
	o.Logo = v
}

// GetDesc returns the Desc field value
func (o *OrganizationDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *OrganizationDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetSort returns the Sort field value
func (o *OrganizationDataAttributes) GetSort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetSortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sort, true
}

// SetSort sets field value
func (o *OrganizationDataAttributes) SetSort(v string) {
	o.Sort = v
}

// GetLinks returns the Links field value
func (o *OrganizationDataAttributes) GetLinks() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetLinksOk() (*Object, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *OrganizationDataAttributes) SetLinks(v Object) {
	o.Links = v
}

// GetComplicatedStatus returns the ComplicatedStatus field value
func (o *OrganizationDataAttributes) GetComplicatedStatus() Object {
	if o == nil {
		var ret Object
		return ret
	}

	return o.ComplicatedStatus
}

// GetComplicatedStatusOk returns a tuple with the ComplicatedStatus field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetComplicatedStatusOk() (*Object, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComplicatedStatus, true
}

// SetComplicatedStatus sets field value
func (o *OrganizationDataAttributes) SetComplicatedStatus(v Object) {
	o.ComplicatedStatus = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrganizationDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrganizationDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o OrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["logo"] = o.Logo
	toSerialize["desc"] = o.Desc
	toSerialize["sort"] = o.Sort
	toSerialize["links"] = o.Links
	toSerialize["complicated_status"] = o.ComplicatedStatus
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *OrganizationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"logo",
		"desc",
		"sort",
		"links",
		"complicated_status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationDataAttributes := _OrganizationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationDataAttributes)

	if err != nil {
		return err
	}

	*o = OrganizationDataAttributes(varOrganizationDataAttributes)

	return err
}

type NullableOrganizationDataAttributes struct {
	value *OrganizationDataAttributes
	isSet bool
}

func (v NullableOrganizationDataAttributes) Get() *OrganizationDataAttributes {
	return v.value
}

func (v *NullableOrganizationDataAttributes) Set(val *OrganizationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDataAttributes(val *OrganizationDataAttributes) *NullableOrganizationDataAttributes {
	return &NullableOrganizationDataAttributes{value: val, isSet: true}
}

func (v NullableOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


