/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmployeeDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeDataAttributes{}

// EmployeeDataAttributes struct for EmployeeDataAttributes
type EmployeeDataAttributes struct {
	// name of employee
	Name string `json:"name"`
	// Description
	Desc string `json:"desc"`
	// User role
	Role string `json:"role"`
	// User created at
	CreatedAt time.Time `json:"created_at"`
}

type _EmployeeDataAttributes EmployeeDataAttributes

// NewEmployeeDataAttributes instantiates a new EmployeeDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeDataAttributes(name string, desc string, role string, createdAt time.Time) *EmployeeDataAttributes {
	this := EmployeeDataAttributes{}
	this.Name = name
	this.Desc = desc
	this.Role = role
	this.CreatedAt = createdAt
	return &this
}

// NewEmployeeDataAttributesWithDefaults instantiates a new EmployeeDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeDataAttributesWithDefaults() *EmployeeDataAttributes {
	this := EmployeeDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *EmployeeDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmployeeDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmployeeDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *EmployeeDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *EmployeeDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *EmployeeDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetRole returns the Role field value
func (o *EmployeeDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmployeeDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmployeeDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o EmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["role"] = o.Role
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *EmployeeDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"role",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeDataAttributes := _EmployeeDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeDataAttributes(varEmployeeDataAttributes)

	return err
}

type NullableEmployeeDataAttributes struct {
	value *EmployeeDataAttributes
	isSet bool
}

func (v NullableEmployeeDataAttributes) Get() *EmployeeDataAttributes {
	return v.value
}

func (v *NullableEmployeeDataAttributes) Set(val *EmployeeDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeDataAttributes(val *EmployeeDataAttributes) *NullableEmployeeDataAttributes {
	return &NullableEmployeeDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


