/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCreateData{}

// EmployeeCreateData struct for EmployeeCreateData
type EmployeeCreateData struct {
	Type string `json:"type"`
	Attributes EmployeeCreateDataAttributes `json:"attributes"`
}

type _EmployeeCreateData EmployeeCreateData

// NewEmployeeCreateData instantiates a new EmployeeCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCreateData(type_ string, attributes EmployeeCreateDataAttributes) *EmployeeCreateData {
	this := EmployeeCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmployeeCreateDataWithDefaults instantiates a new EmployeeCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCreateDataWithDefaults() *EmployeeCreateData {
	this := EmployeeCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *EmployeeCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmployeeCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmployeeCreateData) GetAttributes() EmployeeCreateDataAttributes {
	if o == nil {
		var ret EmployeeCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateData) GetAttributesOk() (*EmployeeCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmployeeCreateData) SetAttributes(v EmployeeCreateDataAttributes) {
	o.Attributes = v
}

func (o EmployeeCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmployeeCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeCreateData := _EmployeeCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeCreateData)

	if err != nil {
		return err
	}

	*o = EmployeeCreateData(varEmployeeCreateData)

	return err
}

type NullableEmployeeCreateData struct {
	value *EmployeeCreateData
	isSet bool
}

func (v NullableEmployeeCreateData) Get() *EmployeeCreateData {
	return v.value
}

func (v *NullableEmployeeCreateData) Set(val *EmployeeCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCreateData(val *EmployeeCreateData) *NullableEmployeeCreateData {
	return &NullableEmployeeCreateData{value: val, isSet: true}
}

func (v NullableEmployeeCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


