/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationData{}

// OrganizationData struct for OrganizationData
type OrganizationData struct {
	// organization id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes OrganizationDataAttributes `json:"attributes"`
	Relationships OrganizationDataRelationships `json:"relationships"`
}

type _OrganizationData OrganizationData

// NewOrganizationData instantiates a new OrganizationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationData(id string, type_ string, attributes OrganizationDataAttributes, relationships OrganizationDataRelationships) *OrganizationData {
	this := OrganizationData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewOrganizationDataWithDefaults instantiates a new OrganizationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDataWithDefaults() *OrganizationData {
	this := OrganizationData{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *OrganizationData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrganizationData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrganizationData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OrganizationData) GetAttributes() OrganizationDataAttributes {
	if o == nil {
		var ret OrganizationDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OrganizationData) GetAttributesOk() (*OrganizationDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OrganizationData) SetAttributes(v OrganizationDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *OrganizationData) GetRelationships() OrganizationDataRelationships {
	if o == nil {
		var ret OrganizationDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *OrganizationData) GetRelationshipsOk() (*OrganizationDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *OrganizationData) SetRelationships(v OrganizationDataRelationships) {
	o.Relationships = v
}

func (o OrganizationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *OrganizationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationData := _OrganizationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationData)

	if err != nil {
		return err
	}

	*o = OrganizationData(varOrganizationData)

	return err
}

type NullableOrganizationData struct {
	value *OrganizationData
	isSet bool
}

func (v NullableOrganizationData) Get() *OrganizationData {
	return v.value
}

func (v *NullableOrganizationData) Set(val *OrganizationData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationData(val *OrganizationData) *NullableOrganizationData {
	return &NullableOrganizationData{value: val, isSet: true}
}

func (v NullableOrganizationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


