/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationCreateData{}

// OrganizationCreateData struct for OrganizationCreateData
type OrganizationCreateData struct {
	Type string `json:"type"`
	Attributes OrganizationCreateDataAttributes `json:"attributes"`
}

type _OrganizationCreateData OrganizationCreateData

// NewOrganizationCreateData instantiates a new OrganizationCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationCreateData(type_ string, attributes OrganizationCreateDataAttributes) *OrganizationCreateData {
	this := OrganizationCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewOrganizationCreateDataWithDefaults instantiates a new OrganizationCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationCreateDataWithDefaults() *OrganizationCreateData {
	this := OrganizationCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *OrganizationCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrganizationCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OrganizationCreateData) GetAttributes() OrganizationCreateDataAttributes {
	if o == nil {
		var ret OrganizationCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateData) GetAttributesOk() (*OrganizationCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OrganizationCreateData) SetAttributes(v OrganizationCreateDataAttributes) {
	o.Attributes = v
}

func (o OrganizationCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *OrganizationCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationCreateData := _OrganizationCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationCreateData)

	if err != nil {
		return err
	}

	*o = OrganizationCreateData(varOrganizationCreateData)

	return err
}

type NullableOrganizationCreateData struct {
	value *OrganizationCreateData
	isSet bool
}

func (v NullableOrganizationCreateData) Get() *OrganizationCreateData {
	return v.value
}

func (v *NullableOrganizationCreateData) Set(val *OrganizationCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationCreateData(val *OrganizationCreateData) *NullableOrganizationCreateData {
	return &NullableOrganizationCreateData{value: val, isSet: true}
}

func (v NullableOrganizationCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


