/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationCreateDataAttributesOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationCreateDataAttributesOwner{}

// OrganizationCreateDataAttributesOwner struct for OrganizationCreateDataAttributesOwner
type OrganizationCreateDataAttributesOwner struct {
	// first name of participant
	FirstName string `json:"first_name"`
	// second name of participant
	SecondName string `json:"second_name"`
	// third name of participant
	ThirdName *string `json:"third_name,omitempty"`
	// name of participant
	DisplayName string `json:"display_name"`
	// position in the company
	Position string `json:"position"`
	// Description
	Desc string `json:"desc"`
}

type _OrganizationCreateDataAttributesOwner OrganizationCreateDataAttributesOwner

// NewOrganizationCreateDataAttributesOwner instantiates a new OrganizationCreateDataAttributesOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationCreateDataAttributesOwner(firstName string, secondName string, displayName string, position string, desc string) *OrganizationCreateDataAttributesOwner {
	this := OrganizationCreateDataAttributesOwner{}
	this.FirstName = firstName
	this.SecondName = secondName
	this.DisplayName = displayName
	this.Position = position
	this.Desc = desc
	return &this
}

// NewOrganizationCreateDataAttributesOwnerWithDefaults instantiates a new OrganizationCreateDataAttributesOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationCreateDataAttributesOwnerWithDefaults() *OrganizationCreateDataAttributesOwner {
	this := OrganizationCreateDataAttributesOwner{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *OrganizationCreateDataAttributesOwner) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *OrganizationCreateDataAttributesOwner) SetFirstName(v string) {
	o.FirstName = v
}

// GetSecondName returns the SecondName field value
func (o *OrganizationCreateDataAttributesOwner) GetSecondName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecondName
}

// GetSecondNameOk returns a tuple with the SecondName field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetSecondNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecondName, true
}

// SetSecondName sets field value
func (o *OrganizationCreateDataAttributesOwner) SetSecondName(v string) {
	o.SecondName = v
}

// GetThirdName returns the ThirdName field value if set, zero value otherwise.
func (o *OrganizationCreateDataAttributesOwner) GetThirdName() string {
	if o == nil || IsNil(o.ThirdName) {
		var ret string
		return ret
	}
	return *o.ThirdName
}

// GetThirdNameOk returns a tuple with the ThirdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetThirdNameOk() (*string, bool) {
	if o == nil || IsNil(o.ThirdName) {
		return nil, false
	}
	return o.ThirdName, true
}

// HasThirdName returns a boolean if a field has been set.
func (o *OrganizationCreateDataAttributesOwner) HasThirdName() bool {
	if o != nil && !IsNil(o.ThirdName) {
		return true
	}

	return false
}

// SetThirdName gets a reference to the given string and assigns it to the ThirdName field.
func (o *OrganizationCreateDataAttributesOwner) SetThirdName(v string) {
	o.ThirdName = &v
}

// GetDisplayName returns the DisplayName field value
func (o *OrganizationCreateDataAttributesOwner) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *OrganizationCreateDataAttributesOwner) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetPosition returns the Position field value
func (o *OrganizationCreateDataAttributesOwner) GetPosition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetPositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *OrganizationCreateDataAttributesOwner) SetPosition(v string) {
	o.Position = v
}

// GetDesc returns the Desc field value
func (o *OrganizationCreateDataAttributesOwner) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *OrganizationCreateDataAttributesOwner) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *OrganizationCreateDataAttributesOwner) SetDesc(v string) {
	o.Desc = v
}

func (o OrganizationCreateDataAttributesOwner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationCreateDataAttributesOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_name"] = o.FirstName
	toSerialize["second_name"] = o.SecondName
	if !IsNil(o.ThirdName) {
		toSerialize["third_name"] = o.ThirdName
	}
	toSerialize["display_name"] = o.DisplayName
	toSerialize["position"] = o.Position
	toSerialize["desc"] = o.Desc
	return toSerialize, nil
}

func (o *OrganizationCreateDataAttributesOwner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"second_name",
		"display_name",
		"position",
		"desc",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationCreateDataAttributesOwner := _OrganizationCreateDataAttributesOwner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationCreateDataAttributesOwner)

	if err != nil {
		return err
	}

	*o = OrganizationCreateDataAttributesOwner(varOrganizationCreateDataAttributesOwner)

	return err
}

type NullableOrganizationCreateDataAttributesOwner struct {
	value *OrganizationCreateDataAttributesOwner
	isSet bool
}

func (v NullableOrganizationCreateDataAttributesOwner) Get() *OrganizationCreateDataAttributesOwner {
	return v.value
}

func (v *NullableOrganizationCreateDataAttributesOwner) Set(val *OrganizationCreateDataAttributesOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationCreateDataAttributesOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationCreateDataAttributesOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationCreateDataAttributesOwner(val *OrganizationCreateDataAttributesOwner) *NullableOrganizationCreateDataAttributesOwner {
	return &NullableOrganizationCreateDataAttributesOwner{value: val, isSet: true}
}

func (v NullableOrganizationCreateDataAttributesOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationCreateDataAttributesOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


