/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeUpdateDataAttributes{}

// EmployeeUpdateDataAttributes struct for EmployeeUpdateDataAttributes
type EmployeeUpdateDataAttributes struct {
	// Organization id
	OrgId string `json:"org_id"`
	// User id
	UserId string `json:"user_id"`
	// name of employee
	Name *string `json:"name,omitempty"`
	// Description
	Desc *string `json:"desc,omitempty"`
	// User role
	Role *string `json:"role,omitempty"`
}

type _EmployeeUpdateDataAttributes EmployeeUpdateDataAttributes

// NewEmployeeUpdateDataAttributes instantiates a new EmployeeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeUpdateDataAttributes(orgId string, userId string) *EmployeeUpdateDataAttributes {
	this := EmployeeUpdateDataAttributes{}
	this.OrgId = orgId
	this.UserId = userId
	return &this
}

// NewEmployeeUpdateDataAttributesWithDefaults instantiates a new EmployeeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeUpdateDataAttributesWithDefaults() *EmployeeUpdateDataAttributes {
	this := EmployeeUpdateDataAttributes{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *EmployeeUpdateDataAttributes) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *EmployeeUpdateDataAttributes) SetOrgId(v string) {
	o.OrgId = v
}

// GetUserId returns the UserId field value
func (o *EmployeeUpdateDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *EmployeeUpdateDataAttributes) SetUserId(v string) {
	o.UserId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmployeeUpdateDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmployeeUpdateDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmployeeUpdateDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *EmployeeUpdateDataAttributes) GetDesc() string {
	if o == nil || IsNil(o.Desc) {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetDescOk() (*string, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *EmployeeUpdateDataAttributes) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *EmployeeUpdateDataAttributes) SetDesc(v string) {
	o.Desc = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *EmployeeUpdateDataAttributes) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *EmployeeUpdateDataAttributes) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *EmployeeUpdateDataAttributes) SetRole(v string) {
	o.Role = &v
}

func (o EmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_id"] = o.OrgId
	toSerialize["user_id"] = o.UserId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *EmployeeUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_id",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeUpdateDataAttributes := _EmployeeUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeUpdateDataAttributes(varEmployeeUpdateDataAttributes)

	return err
}

type NullableEmployeeUpdateDataAttributes struct {
	value *EmployeeUpdateDataAttributes
	isSet bool
}

func (v NullableEmployeeUpdateDataAttributes) Get() *EmployeeUpdateDataAttributes {
	return v.value
}

func (v *NullableEmployeeUpdateDataAttributes) Set(val *EmployeeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeUpdateDataAttributes(val *EmployeeUpdateDataAttributes) *NullableEmployeeUpdateDataAttributes {
	return &NullableEmployeeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


