/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDataRelationships{}

// OrganizationDataRelationships struct for OrganizationDataRelationships
type OrganizationDataRelationships struct {
	Participants OrganizationDataRelationshipsParticipants `json:"participants"`
}

type _OrganizationDataRelationships OrganizationDataRelationships

// NewOrganizationDataRelationships instantiates a new OrganizationDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDataRelationships(participants OrganizationDataRelationshipsParticipants) *OrganizationDataRelationships {
	this := OrganizationDataRelationships{}
	this.Participants = participants
	return &this
}

// NewOrganizationDataRelationshipsWithDefaults instantiates a new OrganizationDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDataRelationshipsWithDefaults() *OrganizationDataRelationships {
	this := OrganizationDataRelationships{}
	return &this
}

// GetParticipants returns the Participants field value
func (o *OrganizationDataRelationships) GetParticipants() OrganizationDataRelationshipsParticipants {
	if o == nil {
		var ret OrganizationDataRelationshipsParticipants
		return ret
	}

	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataRelationships) GetParticipantsOk() (*OrganizationDataRelationshipsParticipants, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Participants, true
}

// SetParticipants sets field value
func (o *OrganizationDataRelationships) SetParticipants(v OrganizationDataRelationshipsParticipants) {
	o.Participants = v
}

func (o OrganizationDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["participants"] = o.Participants
	return toSerialize, nil
}

func (o *OrganizationDataRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"participants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationDataRelationships := _OrganizationDataRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationDataRelationships)

	if err != nil {
		return err
	}

	*o = OrganizationDataRelationships(varOrganizationDataRelationships)

	return err
}

type NullableOrganizationDataRelationships struct {
	value *OrganizationDataRelationships
	isSet bool
}

func (v NullableOrganizationDataRelationships) Get() *OrganizationDataRelationships {
	return v.value
}

func (v *NullableOrganizationDataRelationships) Set(val *OrganizationDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDataRelationships(val *OrganizationDataRelationships) *NullableOrganizationDataRelationships {
	return &NullableOrganizationDataRelationships{value: val, isSet: true}
}

func (v NullableOrganizationDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


