/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantUpdateData{}

// ParticipantUpdateData struct for ParticipantUpdateData
type ParticipantUpdateData struct {
	// user Id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes ParticipantUpdateDataAttributes `json:"attributes"`
}

type _ParticipantUpdateData ParticipantUpdateData

// NewParticipantUpdateData instantiates a new ParticipantUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantUpdateData(id string, type_ string, attributes ParticipantUpdateDataAttributes) *ParticipantUpdateData {
	this := ParticipantUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewParticipantUpdateDataWithDefaults instantiates a new ParticipantUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantUpdateDataWithDefaults() *ParticipantUpdateData {
	this := ParticipantUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *ParticipantUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParticipantUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParticipantUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ParticipantUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ParticipantUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ParticipantUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ParticipantUpdateData) GetAttributes() ParticipantUpdateDataAttributes {
	if o == nil {
		var ret ParticipantUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ParticipantUpdateData) GetAttributesOk() (*ParticipantUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ParticipantUpdateData) SetAttributes(v ParticipantUpdateDataAttributes) {
	o.Attributes = v
}

func (o ParticipantUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ParticipantUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantUpdateData := _ParticipantUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantUpdateData)

	if err != nil {
		return err
	}

	*o = ParticipantUpdateData(varParticipantUpdateData)

	return err
}

type NullableParticipantUpdateData struct {
	value *ParticipantUpdateData
	isSet bool
}

func (v NullableParticipantUpdateData) Get() *ParticipantUpdateData {
	return v.value
}

func (v *NullableParticipantUpdateData) Set(val *ParticipantUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantUpdateData(val *ParticipantUpdateData) *NullableParticipantUpdateData {
	return &NullableParticipantUpdateData{value: val, isSet: true}
}

func (v NullableParticipantUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


