/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationDataRelationshipsParticipants type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDataRelationshipsParticipants{}

// OrganizationDataRelationshipsParticipants struct for OrganizationDataRelationshipsParticipants
type OrganizationDataRelationshipsParticipants struct {
	Links OrganizationDataRelationshipsParticipantsLinks `json:"links"`
}

type _OrganizationDataRelationshipsParticipants OrganizationDataRelationshipsParticipants

// NewOrganizationDataRelationshipsParticipants instantiates a new OrganizationDataRelationshipsParticipants object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDataRelationshipsParticipants(links OrganizationDataRelationshipsParticipantsLinks) *OrganizationDataRelationshipsParticipants {
	this := OrganizationDataRelationshipsParticipants{}
	this.Links = links
	return &this
}

// NewOrganizationDataRelationshipsParticipantsWithDefaults instantiates a new OrganizationDataRelationshipsParticipants object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDataRelationshipsParticipantsWithDefaults() *OrganizationDataRelationshipsParticipants {
	this := OrganizationDataRelationshipsParticipants{}
	return &this
}

// GetLinks returns the Links field value
func (o *OrganizationDataRelationshipsParticipants) GetLinks() OrganizationDataRelationshipsParticipantsLinks {
	if o == nil {
		var ret OrganizationDataRelationshipsParticipantsLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataRelationshipsParticipants) GetLinksOk() (*OrganizationDataRelationshipsParticipantsLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *OrganizationDataRelationshipsParticipants) SetLinks(v OrganizationDataRelationshipsParticipantsLinks) {
	o.Links = v
}

func (o OrganizationDataRelationshipsParticipants) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDataRelationshipsParticipants) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *OrganizationDataRelationshipsParticipants) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationDataRelationshipsParticipants := _OrganizationDataRelationshipsParticipants{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationDataRelationshipsParticipants)

	if err != nil {
		return err
	}

	*o = OrganizationDataRelationshipsParticipants(varOrganizationDataRelationshipsParticipants)

	return err
}

type NullableOrganizationDataRelationshipsParticipants struct {
	value *OrganizationDataRelationshipsParticipants
	isSet bool
}

func (v NullableOrganizationDataRelationshipsParticipants) Get() *OrganizationDataRelationshipsParticipants {
	return v.value
}

func (v *NullableOrganizationDataRelationshipsParticipants) Set(val *OrganizationDataRelationshipsParticipants) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDataRelationshipsParticipants) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDataRelationshipsParticipants) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDataRelationshipsParticipants(val *OrganizationDataRelationshipsParticipants) *NullableOrganizationDataRelationshipsParticipants {
	return &NullableOrganizationDataRelationshipsParticipants{value: val, isSet: true}
}

func (v NullableOrganizationDataRelationshipsParticipants) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDataRelationshipsParticipants) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


