/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ParticipantDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantDataAttributes{}

// ParticipantDataAttributes struct for ParticipantDataAttributes
type ParticipantDataAttributes struct {
	// first name of participant
	FirstName string `json:"first_name"`
	// second name of participant
	SecondName string `json:"second_name"`
	// third name of participant
	ThirdName *string `json:"third_name,omitempty"`
	// name of participant
	DisplayName string `json:"display_name"`
	// position in the company
	Position string `json:"position"`
	// verified status
	Verified string `json:"verified"`
	// description of participant
	Desc string `json:"desc"`
	// User role
	Role string `json:"role"`
	// User updated at
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// User created at
	CreatedAt time.Time `json:"created_at"`
}

type _ParticipantDataAttributes ParticipantDataAttributes

// NewParticipantDataAttributes instantiates a new ParticipantDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantDataAttributes(firstName string, secondName string, displayName string, position string, verified string, desc string, role string, createdAt time.Time) *ParticipantDataAttributes {
	this := ParticipantDataAttributes{}
	this.FirstName = firstName
	this.SecondName = secondName
	this.DisplayName = displayName
	this.Position = position
	this.Verified = verified
	this.Desc = desc
	this.Role = role
	this.CreatedAt = createdAt
	return &this
}

// NewParticipantDataAttributesWithDefaults instantiates a new ParticipantDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantDataAttributesWithDefaults() *ParticipantDataAttributes {
	this := ParticipantDataAttributes{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *ParticipantDataAttributes) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ParticipantDataAttributes) SetFirstName(v string) {
	o.FirstName = v
}

// GetSecondName returns the SecondName field value
func (o *ParticipantDataAttributes) GetSecondName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecondName
}

// GetSecondNameOk returns a tuple with the SecondName field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetSecondNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecondName, true
}

// SetSecondName sets field value
func (o *ParticipantDataAttributes) SetSecondName(v string) {
	o.SecondName = v
}

// GetThirdName returns the ThirdName field value if set, zero value otherwise.
func (o *ParticipantDataAttributes) GetThirdName() string {
	if o == nil || IsNil(o.ThirdName) {
		var ret string
		return ret
	}
	return *o.ThirdName
}

// GetThirdNameOk returns a tuple with the ThirdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetThirdNameOk() (*string, bool) {
	if o == nil || IsNil(o.ThirdName) {
		return nil, false
	}
	return o.ThirdName, true
}

// HasThirdName returns a boolean if a field has been set.
func (o *ParticipantDataAttributes) HasThirdName() bool {
	if o != nil && !IsNil(o.ThirdName) {
		return true
	}

	return false
}

// SetThirdName gets a reference to the given string and assigns it to the ThirdName field.
func (o *ParticipantDataAttributes) SetThirdName(v string) {
	o.ThirdName = &v
}

// GetDisplayName returns the DisplayName field value
func (o *ParticipantDataAttributes) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ParticipantDataAttributes) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetPosition returns the Position field value
func (o *ParticipantDataAttributes) GetPosition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *ParticipantDataAttributes) SetPosition(v string) {
	o.Position = v
}

// GetVerified returns the Verified field value
func (o *ParticipantDataAttributes) GetVerified() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetVerifiedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *ParticipantDataAttributes) SetVerified(v string) {
	o.Verified = v
}

// GetDesc returns the Desc field value
func (o *ParticipantDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *ParticipantDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetRole returns the Role field value
func (o *ParticipantDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ParticipantDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ParticipantDataAttributes) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ParticipantDataAttributes) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ParticipantDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ParticipantDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ParticipantDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ParticipantDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ParticipantDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_name"] = o.FirstName
	toSerialize["second_name"] = o.SecondName
	if !IsNil(o.ThirdName) {
		toSerialize["third_name"] = o.ThirdName
	}
	toSerialize["display_name"] = o.DisplayName
	toSerialize["position"] = o.Position
	toSerialize["verified"] = o.Verified
	toSerialize["desc"] = o.Desc
	toSerialize["role"] = o.Role
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ParticipantDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"second_name",
		"display_name",
		"position",
		"verified",
		"desc",
		"role",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantDataAttributes := _ParticipantDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantDataAttributes)

	if err != nil {
		return err
	}

	*o = ParticipantDataAttributes(varParticipantDataAttributes)

	return err
}

type NullableParticipantDataAttributes struct {
	value *ParticipantDataAttributes
	isSet bool
}

func (v NullableParticipantDataAttributes) Get() *ParticipantDataAttributes {
	return v.value
}

func (v *NullableParticipantDataAttributes) Set(val *ParticipantDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantDataAttributes(val *ParticipantDataAttributes) *NullableParticipantDataAttributes {
	return &NullableParticipantDataAttributes{value: val, isSet: true}
}

func (v NullableParticipantDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


