/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the ParticipantsCollectionLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantsCollectionLinks{}

// ParticipantsCollectionLinks struct for ParticipantsCollectionLinks
type ParticipantsCollectionLinks struct {
	// Link to the current page
	Self *string `json:"self,omitempty"`
	// Link to the next page
	Next *string `json:"next,omitempty"`
}

// NewParticipantsCollectionLinks instantiates a new ParticipantsCollectionLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantsCollectionLinks() *ParticipantsCollectionLinks {
	this := ParticipantsCollectionLinks{}
	return &this
}

// NewParticipantsCollectionLinksWithDefaults instantiates a new ParticipantsCollectionLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantsCollectionLinksWithDefaults() *ParticipantsCollectionLinks {
	this := ParticipantsCollectionLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ParticipantsCollectionLinks) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantsCollectionLinks) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ParticipantsCollectionLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *ParticipantsCollectionLinks) SetSelf(v string) {
	o.Self = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ParticipantsCollectionLinks) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParticipantsCollectionLinks) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ParticipantsCollectionLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *ParticipantsCollectionLinks) SetNext(v string) {
	o.Next = &v
}

func (o ParticipantsCollectionLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantsCollectionLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	return toSerialize, nil
}

type NullableParticipantsCollectionLinks struct {
	value *ParticipantsCollectionLinks
	isSet bool
}

func (v NullableParticipantsCollectionLinks) Get() *ParticipantsCollectionLinks {
	return v.value
}

func (v *NullableParticipantsCollectionLinks) Set(val *ParticipantsCollectionLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantsCollectionLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantsCollectionLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantsCollectionLinks(val *ParticipantsCollectionLinks) *NullableParticipantsCollectionLinks {
	return &NullableParticipantsCollectionLinks{value: val, isSet: true}
}

func (v NullableParticipantsCollectionLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantsCollectionLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


