/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationLinksUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationLinksUpdateData{}

// OrganizationLinksUpdateData struct for OrganizationLinksUpdateData
type OrganizationLinksUpdateData struct {
	// Organization ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes OrganizationLinks `json:"attributes"`
}

type _OrganizationLinksUpdateData OrganizationLinksUpdateData

// NewOrganizationLinksUpdateData instantiates a new OrganizationLinksUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationLinksUpdateData(id string, type_ string, attributes OrganizationLinks) *OrganizationLinksUpdateData {
	this := OrganizationLinksUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewOrganizationLinksUpdateDataWithDefaults instantiates a new OrganizationLinksUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationLinksUpdateDataWithDefaults() *OrganizationLinksUpdateData {
	this := OrganizationLinksUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationLinksUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationLinksUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationLinksUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *OrganizationLinksUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrganizationLinksUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrganizationLinksUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OrganizationLinksUpdateData) GetAttributes() OrganizationLinks {
	if o == nil {
		var ret OrganizationLinks
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OrganizationLinksUpdateData) GetAttributesOk() (*OrganizationLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OrganizationLinksUpdateData) SetAttributes(v OrganizationLinks) {
	o.Attributes = v
}

func (o OrganizationLinksUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationLinksUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *OrganizationLinksUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationLinksUpdateData := _OrganizationLinksUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationLinksUpdateData)

	if err != nil {
		return err
	}

	*o = OrganizationLinksUpdateData(varOrganizationLinksUpdateData)

	return err
}

type NullableOrganizationLinksUpdateData struct {
	value *OrganizationLinksUpdateData
	isSet bool
}

func (v NullableOrganizationLinksUpdateData) Get() *OrganizationLinksUpdateData {
	return v.value
}

func (v *NullableOrganizationLinksUpdateData) Set(val *OrganizationLinksUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationLinksUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationLinksUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationLinksUpdateData(val *OrganizationLinksUpdateData) *NullableOrganizationLinksUpdateData {
	return &NullableOrganizationLinksUpdateData{value: val, isSet: true}
}

func (v NullableOrganizationLinksUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationLinksUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


