/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the OrganizationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationLinks{}

// OrganizationLinks struct for OrganizationLinks
type OrganizationLinks struct {
	// Twitter profile link
	Twitter *string `json:"twitter,omitempty"`
	// Instagram profile link
	Instagram *string `json:"instagram,omitempty"`
	// Facebook profile link
	Facebook *string `json:"facebook,omitempty"`
	// TikTok profile link
	Tiktok *string `json:"tiktok,omitempty"`
	// LinkedIn profile link
	Linkedin *string `json:"linkedin,omitempty"`
	// Telegram profile link
	Telegram *string `json:"telegram,omitempty"`
	// Discord profile link
	Discord *string `json:"discord,omitempty"`
	// Companies website
	Website *string `json:"website,omitempty"`
}

// NewOrganizationLinks instantiates a new OrganizationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationLinks() *OrganizationLinks {
	this := OrganizationLinks{}
	return &this
}

// NewOrganizationLinksWithDefaults instantiates a new OrganizationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationLinksWithDefaults() *OrganizationLinks {
	this := OrganizationLinks{}
	return &this
}

// GetTwitter returns the Twitter field value if set, zero value otherwise.
func (o *OrganizationLinks) GetTwitter() string {
	if o == nil || IsNil(o.Twitter) {
		var ret string
		return ret
	}
	return *o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetTwitterOk() (*string, bool) {
	if o == nil || IsNil(o.Twitter) {
		return nil, false
	}
	return o.Twitter, true
}

// HasTwitter returns a boolean if a field has been set.
func (o *OrganizationLinks) HasTwitter() bool {
	if o != nil && !IsNil(o.Twitter) {
		return true
	}

	return false
}

// SetTwitter gets a reference to the given string and assigns it to the Twitter field.
func (o *OrganizationLinks) SetTwitter(v string) {
	o.Twitter = &v
}

// GetInstagram returns the Instagram field value if set, zero value otherwise.
func (o *OrganizationLinks) GetInstagram() string {
	if o == nil || IsNil(o.Instagram) {
		var ret string
		return ret
	}
	return *o.Instagram
}

// GetInstagramOk returns a tuple with the Instagram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetInstagramOk() (*string, bool) {
	if o == nil || IsNil(o.Instagram) {
		return nil, false
	}
	return o.Instagram, true
}

// HasInstagram returns a boolean if a field has been set.
func (o *OrganizationLinks) HasInstagram() bool {
	if o != nil && !IsNil(o.Instagram) {
		return true
	}

	return false
}

// SetInstagram gets a reference to the given string and assigns it to the Instagram field.
func (o *OrganizationLinks) SetInstagram(v string) {
	o.Instagram = &v
}

// GetFacebook returns the Facebook field value if set, zero value otherwise.
func (o *OrganizationLinks) GetFacebook() string {
	if o == nil || IsNil(o.Facebook) {
		var ret string
		return ret
	}
	return *o.Facebook
}

// GetFacebookOk returns a tuple with the Facebook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetFacebookOk() (*string, bool) {
	if o == nil || IsNil(o.Facebook) {
		return nil, false
	}
	return o.Facebook, true
}

// HasFacebook returns a boolean if a field has been set.
func (o *OrganizationLinks) HasFacebook() bool {
	if o != nil && !IsNil(o.Facebook) {
		return true
	}

	return false
}

// SetFacebook gets a reference to the given string and assigns it to the Facebook field.
func (o *OrganizationLinks) SetFacebook(v string) {
	o.Facebook = &v
}

// GetTiktok returns the Tiktok field value if set, zero value otherwise.
func (o *OrganizationLinks) GetTiktok() string {
	if o == nil || IsNil(o.Tiktok) {
		var ret string
		return ret
	}
	return *o.Tiktok
}

// GetTiktokOk returns a tuple with the Tiktok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetTiktokOk() (*string, bool) {
	if o == nil || IsNil(o.Tiktok) {
		return nil, false
	}
	return o.Tiktok, true
}

// HasTiktok returns a boolean if a field has been set.
func (o *OrganizationLinks) HasTiktok() bool {
	if o != nil && !IsNil(o.Tiktok) {
		return true
	}

	return false
}

// SetTiktok gets a reference to the given string and assigns it to the Tiktok field.
func (o *OrganizationLinks) SetTiktok(v string) {
	o.Tiktok = &v
}

// GetLinkedin returns the Linkedin field value if set, zero value otherwise.
func (o *OrganizationLinks) GetLinkedin() string {
	if o == nil || IsNil(o.Linkedin) {
		var ret string
		return ret
	}
	return *o.Linkedin
}

// GetLinkedinOk returns a tuple with the Linkedin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetLinkedinOk() (*string, bool) {
	if o == nil || IsNil(o.Linkedin) {
		return nil, false
	}
	return o.Linkedin, true
}

// HasLinkedin returns a boolean if a field has been set.
func (o *OrganizationLinks) HasLinkedin() bool {
	if o != nil && !IsNil(o.Linkedin) {
		return true
	}

	return false
}

// SetLinkedin gets a reference to the given string and assigns it to the Linkedin field.
func (o *OrganizationLinks) SetLinkedin(v string) {
	o.Linkedin = &v
}

// GetTelegram returns the Telegram field value if set, zero value otherwise.
func (o *OrganizationLinks) GetTelegram() string {
	if o == nil || IsNil(o.Telegram) {
		var ret string
		return ret
	}
	return *o.Telegram
}

// GetTelegramOk returns a tuple with the Telegram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetTelegramOk() (*string, bool) {
	if o == nil || IsNil(o.Telegram) {
		return nil, false
	}
	return o.Telegram, true
}

// HasTelegram returns a boolean if a field has been set.
func (o *OrganizationLinks) HasTelegram() bool {
	if o != nil && !IsNil(o.Telegram) {
		return true
	}

	return false
}

// SetTelegram gets a reference to the given string and assigns it to the Telegram field.
func (o *OrganizationLinks) SetTelegram(v string) {
	o.Telegram = &v
}

// GetDiscord returns the Discord field value if set, zero value otherwise.
func (o *OrganizationLinks) GetDiscord() string {
	if o == nil || IsNil(o.Discord) {
		var ret string
		return ret
	}
	return *o.Discord
}

// GetDiscordOk returns a tuple with the Discord field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetDiscordOk() (*string, bool) {
	if o == nil || IsNil(o.Discord) {
		return nil, false
	}
	return o.Discord, true
}

// HasDiscord returns a boolean if a field has been set.
func (o *OrganizationLinks) HasDiscord() bool {
	if o != nil && !IsNil(o.Discord) {
		return true
	}

	return false
}

// SetDiscord gets a reference to the given string and assigns it to the Discord field.
func (o *OrganizationLinks) SetDiscord(v string) {
	o.Discord = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *OrganizationLinks) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *OrganizationLinks) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *OrganizationLinks) SetWebsite(v string) {
	o.Website = &v
}

func (o OrganizationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Twitter) {
		toSerialize["twitter"] = o.Twitter
	}
	if !IsNil(o.Instagram) {
		toSerialize["instagram"] = o.Instagram
	}
	if !IsNil(o.Facebook) {
		toSerialize["facebook"] = o.Facebook
	}
	if !IsNil(o.Tiktok) {
		toSerialize["tiktok"] = o.Tiktok
	}
	if !IsNil(o.Linkedin) {
		toSerialize["linkedin"] = o.Linkedin
	}
	if !IsNil(o.Telegram) {
		toSerialize["telegram"] = o.Telegram
	}
	if !IsNil(o.Discord) {
		toSerialize["discord"] = o.Discord
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	return toSerialize, nil
}

type NullableOrganizationLinks struct {
	value *OrganizationLinks
	isSet bool
}

func (v NullableOrganizationLinks) Get() *OrganizationLinks {
	return v.value
}

func (v *NullableOrganizationLinks) Set(val *OrganizationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationLinks(val *OrganizationLinks) *NullableOrganizationLinks {
	return &NullableOrganizationLinks{value: val, isSet: true}
}

func (v NullableOrganizationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


