/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParticipantCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParticipantCreate{}

// ParticipantCreate struct for ParticipantCreate
type ParticipantCreate struct {
	Data ParticipantCreateData `json:"data"`
}

type _ParticipantCreate ParticipantCreate

// NewParticipantCreate instantiates a new ParticipantCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParticipantCreate(data ParticipantCreateData) *ParticipantCreate {
	this := ParticipantCreate{}
	this.Data = data
	return &this
}

// NewParticipantCreateWithDefaults instantiates a new ParticipantCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParticipantCreateWithDefaults() *ParticipantCreate {
	this := ParticipantCreate{}
	return &this
}

// GetData returns the Data field value
func (o *ParticipantCreate) GetData() ParticipantCreateData {
	if o == nil {
		var ret ParticipantCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ParticipantCreate) GetDataOk() (*ParticipantCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ParticipantCreate) SetData(v ParticipantCreateData) {
	o.Data = v
}

func (o ParticipantCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParticipantCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ParticipantCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParticipantCreate := _ParticipantCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParticipantCreate)

	if err != nil {
		return err
	}

	*o = ParticipantCreate(varParticipantCreate)

	return err
}

type NullableParticipantCreate struct {
	value *ParticipantCreate
	isSet bool
}

func (v NullableParticipantCreate) Get() *ParticipantCreate {
	return v.value
}

func (v *NullableParticipantCreate) Set(val *ParticipantCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableParticipantCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableParticipantCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParticipantCreate(val *ParticipantCreate) *NullableParticipantCreate {
	return &NullableParticipantCreate{value: val, isSet: true}
}

func (v NullableParticipantCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParticipantCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


