/*
test

example

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the EmployeeCollectionMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCollectionMeta{}

// EmployeeCollectionMeta struct for EmployeeCollectionMeta
type EmployeeCollectionMeta struct {
	// Total number of employees
	Total *int32 `json:"total,omitempty"`
}

// NewEmployeeCollectionMeta instantiates a new EmployeeCollectionMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCollectionMeta() *EmployeeCollectionMeta {
	this := EmployeeCollectionMeta{}
	return &this
}

// NewEmployeeCollectionMetaWithDefaults instantiates a new EmployeeCollectionMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCollectionMetaWithDefaults() *EmployeeCollectionMeta {
	this := EmployeeCollectionMeta{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *EmployeeCollectionMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCollectionMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *EmployeeCollectionMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *EmployeeCollectionMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o EmployeeCollectionMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCollectionMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableEmployeeCollectionMeta struct {
	value *EmployeeCollectionMeta
	isSet bool
}

func (v NullableEmployeeCollectionMeta) Get() *EmployeeCollectionMeta {
	return v.value
}

func (v *NullableEmployeeCollectionMeta) Set(val *EmployeeCollectionMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCollectionMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCollectionMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCollectionMeta(val *EmployeeCollectionMeta) *NullableEmployeeCollectionMeta {
	return &NullableEmployeeCollectionMeta{value: val, isSet: true}
}

func (v NullableEmployeeCollectionMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCollectionMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


