/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeUpdateData{}

// EmployeeUpdateData struct for EmployeeUpdateData
type EmployeeUpdateData struct {
	// user Id
	Id *string `json:"id,omitempty"`
	Type string `json:"type"`
	Attributes EmployeeUpdateDataAttributes `json:"attributes"`
}

type _EmployeeUpdateData EmployeeUpdateData

// NewEmployeeUpdateData instantiates a new EmployeeUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeUpdateData(type_ string, attributes EmployeeUpdateDataAttributes) *EmployeeUpdateData {
	this := EmployeeUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmployeeUpdateDataWithDefaults instantiates a new EmployeeUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeUpdateDataWithDefaults() *EmployeeUpdateData {
	this := EmployeeUpdateData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmployeeUpdateData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmployeeUpdateData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmployeeUpdateData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value
func (o *EmployeeUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmployeeUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmployeeUpdateData) GetAttributes() EmployeeUpdateDataAttributes {
	if o == nil {
		var ret EmployeeUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateData) GetAttributesOk() (*EmployeeUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmployeeUpdateData) SetAttributes(v EmployeeUpdateDataAttributes) {
	o.Attributes = v
}

func (o EmployeeUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmployeeUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeUpdateData := _EmployeeUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeUpdateData)

	if err != nil {
		return err
	}

	*o = EmployeeUpdateData(varEmployeeUpdateData)

	return err
}

type NullableEmployeeUpdateData struct {
	value *EmployeeUpdateData
	isSet bool
}

func (v NullableEmployeeUpdateData) Get() *EmployeeUpdateData {
	return v.value
}

func (v *NullableEmployeeUpdateData) Set(val *EmployeeUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeUpdateData(val *EmployeeUpdateData) *NullableEmployeeUpdateData {
	return &NullableEmployeeUpdateData{value: val, isSet: true}
}

func (v NullableEmployeeUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


