openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: Created

components:
  schemas:
